# Generated by Django 4.1.3 on 2023-04-15 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_transaction_options_transaction_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedtransaction',
            name='transactionkind',
            field=models.CharField(choices=[('Einnahme', 'Einnahme'), ('Ausgabe', 'Ausgabe')], max_length=200),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionkind',
            field=models.CharField(choices=[('Einnahme', 'Einnahme'), ('Ausgabe', 'Ausgabe')], max_length=200),
        ),
    ]
