# Generated by Django 4.1.3 on 2023-04-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_fixedtransaction_transactionkind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedtransaction',
            name='end_date',
            field=models.DateField(blank=True),
        ),
    ]
