# Generated by Django 4.1.3 on 2023-04-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_fixedtransaction_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixedtransaction',
            name='end_date',
        ),
    ]
